### ISSUE TITLE
Long QT syndromes [Revise subclass]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#2330]
**Mondo term (ID and Label)**
MONDO:0002442
"Long QT syndrome"

**Suggested revision and reasons**
The definition on this parent term describes "The two major forms are Romano-Ward syndrome and Jervell-Lange Nielsen syndrome." and then Children of this term are "Jervell-Lange Nielsen syndrome" and "familial long QT syndrome" (and under this familial long QT term I see "Jervell and Lange-Nielsen syndrome" again)  But there is no specific heading for "Romano-Ward syndrome" but instead this is treated as a synonym to this parent term Long QT syndrome.

UMLS C0035828 for "Romano-Ward syndrome" has Long QT syndromes 1, 2, 3, 5 and 6 as children.
Overall, it looks like a lot of the same diseases/sub-types are repeated/nested in multiple places in the tree. Some overall clean up is probably needed.
![LongQTSynd_MONDOTree_20201118](https://user-images.githubusercontent.com/71083858/99592149-ca07d200-29bd-11eb-8a77-736699ed27d4.png)

Potential hierarchy (though I am not an expert on these concepts, just based on the naming conventions and briefly reviewing OMIM, UMLS concepts, please verify with these sources)
I. Long QT syndromes
  A. Familial Long QT syndromes
      i. Jervell-Lange Nielsen syndrome
          (a-X) JLNS sub-types
      ii. Romano-Ward syndrome
          (a-X) long QT syndrome types 1-X sub-types.
  B. (any idiopathic/non-Familial Long QT types)

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment]
Looks like Romano-Ward syndrome UMLS C0035828 is equivalent to MONDO_0008646 'long QT syndrome 1'.

I excluded the synonym of Romano-Ward syndrome from MONDO:0002442 long QT syndrome

**Comment by nicolevasilevsky** [comment]
I've reorganized this hierarchy a bit:
![image](https://user-images.githubusercontent.com/6722114/101709790-fbb40c00-3a44-11eb-80be-710a04e1d21c.png)


Let me know if you'd like further changes

**Comment by nicolevasilevsky** [comment]
I revised the def for long QT syndrome:

A condition that is characterized by episodes of fainting (syncope) and varying degree of ventricular arrhythmia as indicated by the prolonged QT interval. The inherited forms are caused by mutation of genes encoding cardiac ion channel proteins. The two major forms are Romano-Ward syndrome (also known as long QT syndrome 1) and Jervell-Lange Nielsen syndrome.

**Comment by nicolevasilevsky** [comment]
@kanems I merged these changes, please feel free to reopen if you'd like further changes. :)

**Comment by kanems** [comment]
Hi @nicolevasilevsky I am still not sure the terms in this tree are clarified sufficiently. Sorry it has taken me a while to circle back around to this. 
OrphaNet's Romano Ward Syndrome https://www.orpha.net/consor/cgi-bin/OC_Exp.php?Expert=101016 is a generic concept, not the specific long QT1 syndrome. So the Orphanet ID doesn't belong on MONDO:0008646 with OMIM:192500 (this is another instance of the OrphaNetID incorrectly mapping with ONE of the OMIM-specific subtypes: Ticket [#2693](https://github.com/monarch-initiative/mondo/issues/2693) )

Also I don't think the UMLS term C0035828 is equivalent to Long QT synd. 1 (see this screenshot from UMLS that shows many syns/sources are RWS and long QT1 is a "narrower" (aka child) concept to RWS in the UMLS structure.)
![image](https://user-images.githubusercontent.com/71083858/109210233-8ff75a80-777a-11eb-8a59-e246d4050849.png)

**Comment by nicolevasilevsky** [comment]
Thanks @kanems.

Sounds like we need to split MONDO_0008646 'long QT syndrome 1' into:

-MONDO:0019171 **'familial long QT syndrome'**
--[new term] **Romano-Ward syndrome** ([ORPHA:101016](https://www.orpha.net/consor/cgi-bin/OC_Exp.php?Expert=101016), UMLS: C0035828)
---[obsolete MONDO_0008646 and create new ID] **long QT syndrome 1** ([OMIM:192500](https://omim.org/entry/192500))

I'd like to check with OMIM though, since they have both of these on the same record.

@ahamosh what do you think about the proposed changes above?

**Comment by ahamosh** [comment]
Romano Ward syndrome and Long QT syndrome are synonyms for the parent concept. It can be mapped to either the orpha code 101016 or PS192500.  LQTS1 is OMIM:192500.  When there isn't a phenotypic series, you can map to orphanet.  OMIM always discusses genetic heterogeneity of a phenotype in the lowest number entry.

**Comment by kanems** [comment]
Nicole: Is this something that needs to be discussed at the Workshop, or do you think Ada's comment above it sufficient to clarify what to do with the RWS term?

**Comment by nicolevasilevsky** [comment]
Hi @kanems I'll try to work on this this week. :)

**Comment by nicolevasilevsky** [comment]
Revised to do:
-MONDO:0019171 'familial long QT syndrome' (ORPHA:101016, UMLS: C0035828) - add syns: Romano Ward syndrome and Long QT syndrome
--MONDO_0008646 'long QT syndrome 1' (OMIM:192500)

**Comment by nicolevasilevsky** [comment]
Oh, looking at this more closely though, this is going to cause a proxy merge for Orphanet - Orphanet has a separate called for [Romano Ward syndrome ](https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_101016&viewMode=All&siblings=false).

I'd just like to double check this with @cmungall

**Comment by nicolevasilevsky** [comment]
update- Chris said he is okay with it, I will check with Orphanet too but will proceed with this in Mondo now.

**Comment by nicolevasilevsky** [comment]
emailed @ana-rath-orphanet on 03/31/21.
cc @Orphanet

**Comment by nicolevasilevsky** [comment]
@kanems I plan to do a Mondo release tomorrow, could you please let me know if you see any further issues with this after the release.

**Comment by kanems** [comment]
I’ll take a look, thanks!

**Comment by kanems** [comment]
Hi Nicole! The Romano-Ward syndrome portion of this tree seems to be sorted out. Will ORPHA:101016 just not be treated as an exact X-ref for any Mondo terms now? 

I do have a couple more corrections I think are needed to fully clean up this branch.
![LongQTSynd_MONDOTree_2021_04_19](https://user-images.githubusercontent.com/71083858/115248060-55b09680-a0f5-11eb-8e73-f103374dda37.png)
I.	**MERGE** Jervell-Lange Nielsen syndrome (MONDO:0002441) AND Jervell and Lange-Nielsen syndrome (MONDO:0009078 )
Based on the X-refs they all end up mapping back to synonyms/ cross-citations on  MESH:D029593 / UMLS CUI: C0022387 (See attachment) (so the end results is one merged concept for JLNS with two children: JLNS 1 and JLNS 2)
II.     **CLEAN UP relationships for JLNS/fLQTS** Right now the redundant JLNS concepts are both a sibling AND a child of familial Long QT syndrome.
Long QT syndrome MONDO:0002442 has it’s definition that the 2 major forms are Romano-Ward and JLNS. 
so maybe move JLNS so only a sib. of familial long QT syndrome (aka RWS) 
III.        Within the Familial Long QT syndrome children terms, there is one additional term that is similar but not exactly part of the OMIM PS192500 on FQLTS. : _MIM  601005_, TIMOTHY SYNDROME; TS (MONDO:0010979) Is NOT a child of the MIM PS on fLQTS. (Not sure where to put this, since it’s a familial LQTS and is molecularly related to LQT8, MIM 618447). Maybe this moves to be a child of the parent term "long QT syndrome" since it's not exactly the same as LQT8? I am not sure on this, but just trying to follow the X-refs from the authoritative sources.
[2021_04_19_FamilialLongQT-JLNS.docx](https://github.com/monarch-initiative/mondo/files/6336567/2021_04_19_FamilialLongQT-JLNS.docx)

**Comment by sabrinatoro** [comment]
To do : 
- [ ]  MERGE Jervell-Lange Nielsen syndrome (MONDO:0002441) AND Jervell and Lange-Nielsen syndrome (MONDO:0009078 )
This was address in #3073 

- [ ] On 'Jervel and Lange-Nielsen syndrome’ (MONDO:0002441): Exclude subclass of 'familial long QT syndrome' 
This way, this term is ONLY a sibling of 'familial long QT syndrome' (aka RWS)-and not both a sibling and a child.

- [ ]  Timothy syndrome (MONDO:0010979): 
- - [ ] exclude subclass “familial long QT syndrome” (therefore TS is only a child of long QT syndrome)
- - [ ] make ‘long QT syndrome type 8 (Orphanet:65283)’ a **related** synomym (instead of a ‘exact synonym’)
